### ISSUE TITLE
Private data not found on separate tabs

### ISSUE THREAD

**Issue by kkmanos** [wwWallet/wallet-ecosystem#31]
The following scenario can be used to reproduce the error "Private data not found"

1. Sign up to wwWallet
2. Open a new tab and navigate to http://localhost:3000
3. Attempt to receive a Verifiable ID credential
4. "Private data not found" error occurs on the step where the browser will attempt to sign the proof jwt after being redirected to the wallet.

This error occurs with both authentication mechanisms (Username/Password and WebAuthn)

**Comment by emlun** [comment]
This is probably because [`sessionStorage` is unique per tab](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage). We probably need to move to using a different storage mechanism for the session contents.

The question then is how we can limit the lifetime of the sensitive wallet contents - `localStorage` has no expiration time and data in `IndexedDB` has only loosely defined lifetimes. Perhaps we could store data in `localStorage` encrypted under a key stored in a cookie? It would have to be architected such that the cookie key alone is not enough to decrypt the wallet contents, since the cookie could be sent to the backend, but I think that could be done. Although MDN does note that [cookie expiration limits are also not necessarily reliable](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#write_a_new_cookie), as users may configure a browser to not expire cookies.

**Comment by kkmanos** [comment]
I think we could avoid this complexity by just asking the user for authentication when the session storage is empty.

What is your view on this?

**Comment by emlun** [comment]
Sure, we could do that. But will it be an acceptable user experience to have to re-authenticate every time you open a new tab?

But I guess we could defer the re-authentication until the app attempts to access encrypted data. Perhaps that's unintrusive enough. In that case - should we consider dropping the session keys entirely, and always have the user re-authenticate every time the app needs access to encrypted data (i.e., every time a signing operation is needed)?

**Comment by emlun** [comment]
Otherwise, if we want to keep the encrypted data available without re-auth for the duration of the session, we could use a technique mentioned [here](https://stackoverflow.com/a/32766809). In short, use `localStorage` events to transfer data between `sessionStorage` instances. We could probably do something like this:

- When the user logs in, the wallet contents are downloaded, re-encrypted and stored in `localStorage`. The re-encryption key for the session is stored in `sessionStorage`.
- When the user opens a new tab and the code attempts to access the encrypted data in `localStorage` but a session encryption key does not exist in the tab's `sessionStorage`, the new tab writes a new key `request-session-key-${uuid}` into `localStorage`.
- The existing tab listens for storage events on `localStorage` and intercepts the `request-session-key-*` write event. This tab creates a new session key, re-encrypts the wallet contents under this key and writes the new session key as `response-session-key-${uuid}` into `localStorage`.
- The new tab listens for storage events on `localStorage` and intercepts the `response-session-key-*` write event. This tab copies the new session key from `localStorage` to `sessionStorage` and then deletes both `request-session-key-*` and `response-session-key-*` keys from `localStorage`.

I think something like that could work - that way the wallet will be closed once all session keys are deleted, so the sensitive contents do not remain available while the browser is closed. We should probably also encrypt the `response-session-key-*` value with another ephemeral key kept in session storage, just in case the browser crashes while the new session key exists in `localStorage`, but that's a simple addition to the protocol.

Hm... but on the other hand, how does each tab know if there is any other tab that could respond to the key request? Start a short timer, and fall back to re-authentication if the request isn't fullfilled within, say, 500 ms?

Yeah, perhaps it's best to just re-authenticate the user for each new tab as needed.

**Comment by emlun** [comment]
Coming back to this: I think that re-authenticating the user when session storage is empty seems like a reasonable solution, if needed we can iterate on it later. I'll start prototyping this now, let me know if we should consider a different approach.
